version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        ports:
            - '3000:3000' # Next.js web app
            - '3001:3001' # NestJS API
        volumes:
            - .:/app
            - /app/node_modules
            - /app/apps/web/node_modules
            - /app/apps/api/node_modules
            - /app/packages/ui/node_modules
            - /app/packages/eslint-config/node_modules
            - /app/packages/typescript-config/node_modules
        env_file:
            - .env.docker
        environment:
            - NODE_ENV=development
        command: pnpm dev
        stdin_open: true
        tty: true
        depends_on:
            - postgres
            - redis

    # Optional services for development
    postgres:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: mindnote_dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        ports:
            - '5432:5432'
        volumes:
            - postgres_dev_data:/var/lib/postgresql/data

    redis:
        image: redis:7-alpine
        ports:
            - '6379:6379'
        volumes:
            - redis_dev_data:/data

volumes:
    postgres_dev_data:
    redis_dev_data:
